[package]
name = "word-counter"
version = "0.1.0"
edition = "2021"

[dependencies]
postgres = "0.19.7"
uuid = "1.9.1"
axum = { version = "0.7.7" }
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.0", features = ["full"] }